export const LOAD_TABLES = "LOAD_TABLES";
export const ADD_CONNECTION = "CREATE_CONNECTION";
export const LOAD_KEYSPACES = "LOAD_KEYSPACES";
export const LOAD_TABLE_META_DATA = "LOAD_TABLE_META_DATA";
export const LOAD_CONNECTIONS = "LOAD_CONNECTIONS";
export const OPEN_CONNECTION = "OPEN_CONNECTION";
export const CLOSE_CONNECTION = "CLOSE_CONNECTION";
export const CLEAR_TABLE_META_DATA = "CLEAR_TABLE_META_DATA";
